### ISSUE TITLE
Add BUILD_PDF flag

### ISSUE THREAD

**Issue by rgieseke** [greenelab/manubot-rootstock#122]
To work-around PDF build issues (#120) and for quicker local development a `BUILD_PDF` flag like `BUILD_DOCX` might be useful.

This would require skipping "manuscript.pdf" in `webpage.py`, would that be a problem?

**Comment by dhimmel** [comment]
For now, I'd just comment out the PDF section of `build.sh`. In the future, I agree we should add flags or env variables for all the different outputs types.

However, I am thinking that we should migrate more functionality to the Python package. Specifically, we'd have multiple manubot commands

+ `manubot prepare` (what manubot currently does)
+ `manubot output` which would run pandoc and could accept `--html`, `--latex`, `--jats`, `--docx` flags
+ `manubot webpage` which would do what's in `webpage.py` currently
+ `manubot deploy` which would be called by CI presumably to deploy

Still lot's of thinking to do, but given these plans I think it makes sense to hold off on a `BUILD_PDF` env variable for the time being.
