### ISSUE TITLE
Point out that OWNER is case sensitive

### ISSUE THREAD

**Issue by Benjamin-Lee** [greenelab/manubot-rootstock#137]
`OWNER=benjamin-lee` resulted in 

```
Benjamins-MacBook-Pro-9:ci BenjaminLee$ travis encrypt-file   --repo=$OWNER/$REPO   --force   deploy.key > travis-encrypt-file.log
repository not known to https://api.travis-ci.org/: benjamin-lee/ten_simple_rules_for_ml_in_bio
```

whereas `travis encrypt-file   --repo=Benjamin-Lee/$REPO   --force   deploy.key > travis-encrypt-file.log` worked.

**Comment by agitter** [comment]
@Benjamin-Lee thanks for pointing out that this was a confusing part of the setup guide.  I'll make a pull request to update the guide.  Please let us know if you have any other trouble with Manubot.

**Comment by dhimmel** [comment]
Thanks @agitter for the documentation PR and thanks @Benjamin-Lee for the report. I hadn't thought about this capitalization issue before, but it seems like you're GitHub username is `@Benjamin-Lee` and not `@benjamin-lee`. While GitHub is permissive in matching different cases to the canonical casing, Travis is not.

Mostly unrelated... have you considered changing your GitHub username to `@benjamin-lee`? I recommend avoiding uppercase in handles to prevent issues like this. Note that this change may mess with your Travis config... not sure.
