### ISSUE TITLE
SVG images fail to export to PDF

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#14]
Refs https://github.com/jgm/pandoc/issues/265

**Comment by slochower** [comment]
That thread seems to indicate a problem going through LaTeX, but I think the problem persists if we do Markdown → HTML5 → PDF as is currently implemented. Are you considering creating a local rasterized copy of the graphics to generate the PDF? Something like this may be helpful: https://gist.github.com/jeromerobert/3996eca3acd12e4c3d40

**Comment by dhimmel** [comment]
> Markdown → HTML5 → PDF

Yes, I agree that the problem is occurring for this lineage.

> Are you considering creating a local rasterized copy of the graphics to generate the PDF?

I think there should be a solution that doesn't require rasterizing vectors. For example, if an SVG is converted to PDF, then it should be able to be embedded in a PDF without sacrificing the vectors?

**Comment by slochower** [comment]
> For example, if an SVG is converted to PDF, then it should be able to be embedded in a PDF without sacrificing the vectors?

I hope so. Can you make a PDF version of the SVG file we're using for the figure example, built from the same source as the SVG?

**Comment by vsmalladi** [comment]
Should there be a local directory for the figures in the repository?

**Comment by dhimmel** [comment]
@vsmalladi see discussion on https://github.com/greenelab/manubot-rootstock/issues/1: currently we're focusing on images via URL. In #1, @slochower has a working solution for images via paths, but we didn't see a pressing need that justified the complexity.

**Comment by vsmalladi** [comment]
@dhimmel thanks for the brining me up to speed.

**Comment by vsmalladi** [comment]
Accidentally
 put this in the wrong place: [index.pdf](https://github.com/greenelab/manubot-rootstock/files/1185668/index.pdf)


I have been playing with the using wkhtmltopdf and converting the images to png to get them to render for the pdf, based on code in #40. I have attached an example of converting from markdown to html5.

**Comment by agitter** [comment]
@vsmalladi The figures show up, so that's a big improvement.  All text and figures are tiny when I view the pdf though.  Do you see that as well?

**Comment by vsmalladi** [comment]
@agitter Ya I had the same issue. Wanted to see if anyone else saw the same thing. Not sure what is happening with the scaling. But it is looking better.

**Comment by dhimmel** [comment]
Export of SVG images to PDFs should now be working (since we switched to WeasyPrint in https://github.com/greenelab/manubot-rootstock/pull/78). Let us know if your experience is otherwise and we can reopen this issue or start a new issue.
