### ISSUE TITLE
czi-seed-rfa missing root-level gh-pages files

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#143]
@cgreene alerted me to a potential Manubot malfunction where `index.html` and `manuscript.pdf` are missing from the `gh-pages` branch of `greenelab/czi-seed-rfa`, a manubot manuscript repo. See for [example here](https://github.com/greenelab/czi-seed-rfa/tree/169c071d6fe443e321e37af1d84c5c738b201f44). The versioned gh-pages directories still seem to be getting created properly, so a temporary user-facing workaround is to access the latest version with the URL https://greenelab.github.io/czi-seed-rfa/v/latest/.

**Comment by dhimmel** [comment]
The commit where these files first disappeared seems to be https://github.com/greenelab/czi-seed-rfa/commit/f5fef7f07b41dad0cec8e126efa4931ea12e4406, which was the `gh-pages` deployment commit triggered by https://github.com/greenelab/czi-seed-rfa/commit/9dff46fcbc4e5c70fb070a734d2bbe6b0a45bf86. All https://github.com/greenelab/czi-seed-rfa/commit/9dff46fcbc4e5c70fb070a734d2bbe6b0a45bf86 did was add a line to .gitignore, which at quick glance does not seem problematic.

**Comment by dhimmel** [comment]
Unrelated but wanted to note, the Travis CI - Branch build is attempting to run the deployment and failing.
See https://travis-ci.com/greenelab/czi-seed-rfa/builds/90217844#L750:

```
$ test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sh ci/deploy.sh
M	webpage/README.md
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
iv undefined
```

The [push build](https://travis-ci.org/greenelab/czi-seed-rfa/builds/450680756) is okay. I need to look into why there are two builds here.

**Comment by dhimmel** [comment]
Ah I think I see what happened. https://github.com/greenelab/czi-seed-rfa/commit/ec018b74379ab95772c8d536e90ce8c04196ef32 deleted three symbolic links from the master branch: `webpage/images`, `webpage/index.html`, and `webpage/manuscript.pdf`. These symlinks are required.

**Comment by dhimmel** [comment]
I opened a PR at https://github.com/greenelab/czi-seed-rfa/pull/3 that should resolve the issue.

@Loyale do you remember why you deleted the symlinks in the webpage directory in https://github.com/greenelab/czi-seed-rfa/commit/ec018b74379ab95772c8d536e90ce8c04196ef32? I am guessing it was because you thought they were junk (since you also removed `.DS_Store` files in this commit). Perhaps there is a way we can improve the documentation so other users don't do this (unintentionally) in the future.

**Comment by agitter** [comment]
@dhimmel could we make the Travis CI build fail if these or any other essential files or symlinks are missing?

**Comment by Loyale** [comment]
Did I do this through the .gitignore? I don’t remember removing symlinks explicitly, although I wouldn’t put it past myself...

Cheers,
Loyal

________________________________________
Loyal A. Goff, Ph.D.
Assistant Professor
Institute of Genetic Medicine
Johns Hopkins School of Medicine
MRB 449
733 N Broadway
Baltimore, MD 21205
loyalgoff@jhmi.edu
________________________________________

**Comment by Loyale** [comment]
So actually looking at the commit, I have no recollection of doing those deletions. So yeah, my bad. Thanks for the fix.

Cheers,
Loyal

________________________________________
Loyal A. Goff, Ph.D.
Assistant Professor
Institute of Genetic Medicine
Johns Hopkins School of Medicine
MRB 449
733 N Broadway
Baltimore, MD 21205
loyalgoff@jhmi.edu
________________________________________
