### ISSUE TITLE
Separate original pandoc CSS from manubot modified CSS?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/manubot-rootstock#156]
I'm thinking it may be helpful to separate the two somehow, either by putting our (manubot) CSS overrides at the bottom of `github-pandoc.css`, or even just in a separate css file. Or maybe in the html file insert I am writing to generate the tooltips, which also contains its own CSS for the tooltips.

Are there any objections to this? Also does someone have a quick summary of the CSS we "slowly modified over time", or would I have to go through the commits.

**Comment by slochower** [comment]
No objection, but I'm not sure `github-pandoc.css` is really "pandoc CSS" in any sense. I think it's really just a CSS file that we pass to `pandoc` to make the rendered HTML look GitHub-like.

**Comment by vincerubinetti** [comment]
Yes, sorry, I didn't notice that that stylesheet wasn't authored by pandoc themselves. Regardless, it might be wise to separate our modifications from any third party dependencies. Makes it more clear which party modified which thing, and makes it easier to update the dependencies separately without breaking/forgetting anything.

**Comment by dhimmel** [comment]
The gist we copied github-pandoc.css from hasn't been updated in years. It was just a file someone posted and doesn't seem to be maintained.

Perhaps we could compare the file to its original version when added to this repo (ignoring whitespace). There haven't been too many changes.

Do you think github-pandoc.css is good or it's something we may want to rewrite from scratch.

**Comment by vincerubinetti** [comment]
I'll review the css further today, but it seems relatively fine to me. Nothing jumps out at me as bad/dated, in terms of "code quality". 

That being said, it doesn't really look exactly like Github, if that's what we're going for. (Maybe it did look like it at the time it was written?). Having 2-3 themes of the most popular/common options, like Github, that PubCSS, etc per [#Issue 112](https://github.com/greenelab/manubot-rootstock/issues/112) might not actually be a bad idea. I could probably knock them out in 1-2 days per theme.

**Comment by dhimmel** [comment]
As far as I'm aware, we are not interested in making our manuscripts adhere to the GitHub theme. It seems like the [original gist](https://gist.github.com/dashed/6714393) does have this objective. However, I think we just care about making a nice interface to read and interact with articles. When I named the file `github-pandoc.css`, I think I meant `github-pages-pandoc.css`. We could consider renaming this file to anything, if that would help remove confusion over its scope and goals.

**Comment by vincerubinetti** [comment]
Closed due to complete rewrite of CSS theme.

**Comment by dhimmel** [comment]
See https://github.com/greenelab/manubot-rootstock/pull/171 for "complete rewrite of CSS theme"
