### ISSUE TITLE
Update manual reference guidelines with link to examples

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#28]
[This page](https://github.com/aurimasv/zotero-import-export-formats/blob/a51c342e66bebd97b73a7230047b801c8f7bb690/CSL%20JSON.json) provides some nice examples of the CSL metadata for different document types. Would be nice to add to docs.

**Comment by vsmalladi** [comment]
@dhimmel where were you thinking of putting this?

**Comment by dhimmel** [comment]
Somewhere [here](https://github.com/greenelab/manubot-rootstock/tree/master/references#reference-overrides)? Feel free to make the doc PR

**Comment by vsmalladi** [comment]
Sounds good. Will work on it.
