### ISSUE TITLE
Increase top page margin in print media

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#38]
The printed page margin was a bit too small on the top for the Sci-Hub manuscript. PeerJ applied their own banner which overlaps with some of the text. See https://peerj.com/preprints/3100v1.pdf

For example,

![screen shot 2017-07-20 at 8 45 54 pm](https://user-images.githubusercontent.com/1117703/28444615-77f594b6-6d8c-11e7-8aaf-0489d241d4ff.png)

The other margins looked fine.

**Comment by agitter** [comment]
Seems like a good idea.  I've see that happen with some PDFs at bioRxiv as well.  Was this the version of the PDF printed from Chrome?

The authors page looks great on a live preprint.

**Comment by dhimmel** [comment]
> Was this the version of the PDF printed from Chrome?

Printed to PDF using Chrome on Mac. I initially used Chrome on Linux, but the result was not as pretty... some of the spacing between characters seemed off.
