### ISSUE TITLE
Prepended file numbers

### ISSUE THREAD

**Issue by jspauld** [greenelab/manubot-rootstock#41]
It seems like it would be better to specify the ordering of the markdown files by having a separate file.

As it is now it looks like people would have to rename several files if they wanted to change the ordering or add some content in the middle.

**Comment by agitter** [comment]
You're right that it would get ugly to add suffixes like `03a_section.md`, `03b_section.md`, etc. to reorder files without renaming everything.  Technically speaking, it would be a simple modification.  However, I'm not sure that we want to add another file to manage that could introduce errors if users mismatch the filenames in the ordering file and the actual filenames.

What do others think?  For anyone else weighing in, the current behavior comes from `citations.get_text`:
```python
paths = sorted(section_dir.glob('[0-9]*.md'))
```

**Comment by vsmalladi** [comment]
I agree i think another file to manage will cause more issues. Could we add links at the bottom of every markdown to give context of the order from one section to the next one and the previous section?

**Comment by jspauld** [comment]
I'm not entirely sure how this all works.. but just throwing a couple thoughts out:

You could have just one index.md file, and then if people want to they can use the standard templating language to include other files from there. This would leave open the possibility for the simple case where people might want to write their article in one file.

Another thought: I imagine as far as tracking changes (in git) it is more logical to see that some sections were reordered by seeing a change in the content of the files, rather than just the renaming of the files.

**Comment by agitter** [comment]
> Could we add links at the bottom of every markdown

If I understand correctly, would this be like a linked list?  That could also be error-prone.

> You could have just one index.md file, and then if people want to they can use the standard templating language to include other files from there.

That sounds like what I often see in multi-file LaTeX papers.  That solution has worked well for me in LaTeX and could be an option here.  It would make the parsing code more complex so we'd have to weigh the demand versus the implementation and maintenance burden.

**Comment by dhimmel** [comment]
Hey @jspauld. Thanks for checking out this repo!

Another benefit of ordering-by-filename is that file browsers / GitHub will display the files in the same order that they get compiled in.

I don't think the renaming of files (i.e. having to do a few `git mv` commands occasionally) is overly problematic. And I think alternatives will introduce more complexity, hence chance for error and a greater learning barriers.

In cases where renaming many files is not an option, I think the `030.section.md` / `031.section.md` workaround is sufficient. Another option would be leaving gaps to fill in later in the numbers. Or if this is still really a worry, we could write a small script to automatically rename the files. For these reasons, I'm going to close this issue.

@jspauld if you really want to make a contribution, let me know... there are many issues I can open that would aim to apply some of the nice user interface features of https://think-lab.github.io/p/rephetio/ to the HTML output.
