### ISSUE TITLE
Error during build if there are zero references

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot-rootstock#47]
I've been playing around with manually building a manuscript based off this template and noticed that if I have absolutely zero references in my document, I get a build error. If I add a reference in any section (e.g., putting [@doi:10.1126/science.1127344] as a placeholder in my abstract), then the error goes away. 
```
$ bash build/build.sh 
Retrieving and processing reference metadata
Using metadata cache: True
Traceback (most recent call last):
  File "references.py", line 111, in <module>
    ref_df['standard_citation'], ref_df['citation_id'] = zip(*result)
ValueError: not enough values to unpack (expected 2, got 0)
```

I haven't debugged the code, but I think `result` (calculated on line 109, just above the error) is empty when there are no references. Would a simple check `if result not None: ...` before line 111 be a workaround?

```python
result = ref_df.citation.apply(
    get_standard_citatation, cache=metadata_cache, override=overrides)
```
(FWIW, I do get the "potentially misformatted references" error in any case, but the build continues successfully after I add the placeholder. The warning from the templates in the front matter.)

**Comment by dhimmel** [comment]
Hey @slochower I'm doing a major overhaul of the python codebase in https://github.com/greenelab/manubot/pull/2. I will make sure the new codebase works with zero references... it should... it's a lot more robust.

Thanks for the report.

**Comment by vsmalladi** [comment]
@dhimmel Should we start reporting issues to [greenelab/manubot](https://github.com/greenelab/manubot) instead of this repo?

**Comment by dhimmel** [comment]
> Should we start reporting issues to greenelab/manubot instead of this repo?

Some of the issues. In the current design, `greenelab/manubot` will perform the creation of the markdown manuscript and bibliography. However, the pandoc conversion and deployment will still occur in this repository. One goal though is to package as much of the functionality as we can into `greenelab/manubot`.
