### ISSUE TITLE
Symlink CSS to output directory for local viewing of the HTML

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot-rootstock#58]
I propose we symlink `github-pandoc.css` to the `output/` directory so that local building and viewing of `webpage/index.html` or `output/manuscript.html` (I know those are symlinks of each other) loads the CSS. Viewing the HTML from either `webpage/` or `output/` currently can't find the CSS because the browser follows the symlink into `output/` and therefore doesn't find `webpage/github-pandoc.css`. Does that make sense? A simple `ln -s ../webpage/github-pandoc.css` in `output/` fixes the issue.

**Comment by slochower** [comment]
Existing behavior
![image](https://user-images.githubusercontent.com/5393995/29590753-36dd0904-8750-11e7-96ce-5c2608d5e373.png)

After symlink
![image](https://user-images.githubusercontent.com/5393995/29590759-4664dadc-8750-11e7-8240-51d385cbc437.png)

**Comment by dhimmel** [comment]
What is the motivation to have the webpage hosted in both the `webpage` and `output` directory? I prefer having a single directory for the webpage and not duplicating functionality. Especially as the webpage machinery becomes more advanced, we may find ourselves really cluttering the `output` directory. Currently, `output` consists only of Manubot created files (and a README). I don't think it makes sense to change that scope.

If we were to enable webpage viewing from the `output` directory, we might as well just delete `webpage` entirely? But again, I think the delineation between `webpage` and `output` is helpful.

**Comment by slochower** [comment]
> What is the motivation to have the webpage hosted in both the webpage and output directory?

Err, I don't think I want that. But by using symlinks the way they are setup now, viewing the webpage from either directory will not load the correct CSS. 

If you load the webpage in `webpage/` then because `index.html` links to `../output/manuscript.html`, the browser looks for `github-pandoc.css` in `../output/`. Since it's not there, the webpage doesn't render nicely. And if you load the webpage in `output/`, the browser *still* looks for the CSS in `output/` where it's not. Unless my setup has somehow diverged from yours, you should be able to confirm this by opening either HTML file locally.

**Comment by dhimmel** [comment]
The website is only meant to be viewed from the `webpage` directory. It's also not designed to be able to just open the HTML file in the web browser and have it work. You need to set up a web server:

```sh
# View the manuscript locally at http://localhost:8000/
cd webpage
python -m http.server
```

If you do this, http://localhost:8000/ should then display your manuscript? You can refresh the page whenever `manuscript.html` has been updated to see the latest version.

**Comment by slochower** [comment]
But why would I want to start a webserver when one symlink lets me view it locally perfectly? What is the advantage of running the http server?

**Comment by dhimmel** [comment]
> But why would I want to start a webserver when one symlink lets me view it locally perfectly?

I'm not really an expert here, there are [some differences](https://stackoverflow.com/questions/40204913/difference-between-localhost-and-opening-html-file). Basically, opening via a server is going to more closely replicate the behavior of the GitHub Pages site. In my experience, most webpages need to be hosted via server to fully work... but that doesn't mean the convenience of local file opening wouldn't be nice.

I think the real issue here has to do with how the symlink is getting resolved before being opened in your browser. If I open `file:///absolute_path_here/webpage/index.html` in Chrome (so `webpage/index.html` is opened), then the CSS is loaded. Is this workaround sufficient? I pasted this URL manually in the browser navigation bar. I couldn't find a way to script it with `xdg-open` without redirecting.

**Comment by slochower** [comment]
> I think the real issue here has to do with how the symlink is getting resolved before being opened in your browser.

Agreed & I can reproduce the effect. If I open the file directly using `xdg-open` or whatever, then the symlink must get followed first and change the working directory. But if, as you say, I paste in the file location, then it works.

> Basically, opening via a server is going to more closely replicate the behavior of the GitHub Pages site.

Okay, that is fair. For documents that get complicated quickly, where I'm flipping between sections and modifying figures, I wanted a way to quickly view the rendered result. I configured `vscode` with a build task that runs `"command": "cd .. && source activate manubot && bash build/build.sh",` to compile the manuscript when I hit `Ctrl + Shift + B` while writing a section and then I can view it side-by-side with a browser open to http://localhost:8000.

**Comment by dhimmel** [comment]
> I wanted a way to quickly view the rendered result

It would be nice to have an method that monitors for any source changes, and then rebuilds the manuscript automatically. Something like pelican's [`--autoreload`](http://docs.getpelican.com/en/3.6.3/publish.html#site-generation) argument. This would essentially automatically do your `Ctrl + Shift + B` whenever you saved source code changes. Then all you'd have to do is refresh the corresponding webpage in your browser to see the latest.

**Comment by slochower** [comment]
This is the first commit where `pelican` introduced the `--autoreload` feature.
https://github.com/getpelican/pelican/commit/b8fb45de9e512c8c9fc729647a8a843fda6714fc <https://github.com/getpelican/pelican/commit/b8fb45de9e512c8c9fc729647a8a843fda6714fc>
It seems like they are monitoring files by modification time, using the `os` module in python. I don’t think it would be too hard to implement a rudimentary version of this. Maybe we can just check the modification time of the `*.md` files every minute or so, although that introduces the idea of creating a daemon-like version of manubot. So would you imagine running something like `manubot --daemon` to have it persistently check for modification and run the build script? If we wanted to be really fancy, we could also build the HTML with a refresh tag (https://www.w3schools.com/tags/att_meta_http_equiv.asp <https://www.w3schools.com/tags/att_meta_http_equiv.asp>) that would fetch a new version of the page at intervals.

**Comment by dhimmel** [comment]
Perhaps we can use [watchdog](https://github.com/gorakhargosh/watchdog) to rerun `build.sh` upon changes to `content/*`? Seems like this will be the most versatile solution... and it's pip installable.

**Comment by slochower** [comment]
Yeah, I took a look. At what point do you think the watchdog should enter the fray? Something like [this](https://stackoverflow.com/a/18599427) could work, but I'm not sure where we'd implement that; I guess it could be integrated into the `manubot` part.

**Comment by dhimmel** [comment]
> At what point do you think the watchdog should enter the fray?

I was thinking just running the following in manubot rootstock (rather than the current `sh build/build.sh`)

```sh
watchmedo shell-command \
  --pattern=content/** \
  --command='sh build/build.sh' \
  --wait
```

I haven't tested the above code. Once we do, we should be able to make a script such as `build/autoreload.sh`.

**Comment by slochower** [comment]
Yup, got it work with the slightly modified:

```bash
watchmedo  shell-command \
  --patterns='*' \
  --wait \
  --command='sh build/build.sh' \
  content/
```

**Comment by dhimmel** [comment]
I'd like to close this issue. One solution would be to add the following to "Local execution" in the README:

```sh
# Alternatively, you can copy URL produced below into your browser
echo file://`pwd`/webpage/index.html
```

While this works in Chrome, it doesn't in Firefox, since Fireforx doesn't [respect symlinks](http://forums.mozillazine.org/viewtopic.php?f=38&t=2564285) and instead resolves them fully. I haven't tested IE or Safari. @slochower do you think this addition is worth it given its limitations, or we should just close this issue as Won't Fix.

**Comment by slochower** [comment]
I think we should close it, given #61.
