### ISSUE TITLE
Simplifying authors.tsv to manuscript conversion

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#7]
Currently author parsing is disabled in this repo. I'm thinking of simplifying the TSV format and how it gets added to the manuscript. Basically, here would be the columns:

+ github_username
+ full_name
+ initials (possibly)
+ orcid
+ affiliations
+ funding
+ email
+ symbols (superscript symbols to add next to name). Could be symbol for corresponding or contributed equally. Or anything. The symbols would be manually defined in the mardown doc.

I was thinking of removing the `approve` column, and going for each author submits a PR to add their name, hence approving.

Unlike the system [for the deep review](https://github.com/greenelab/deep-review/blob/b7ebb0ac4ebf981d14b2b6e6e0af6c23cd80c2e7/authors.tsv), the build system, would not try to condense affiliations or funding across authors. In other words, each author would get their details printed next to their name. There would be more duplication of text, but this system will be more reliable. Additionally, we may eventually move to putting much of this info in tooltips for the HTML version.

@agitter what do you think. Feel free to disagree!

**Comment by dhimmel** [comment]
Another consideration is that we should fill out the pandoc author metadata as discussed in https://github.com/greenelab/manubot-rootstock/issues/4#issuecomment-313877812. We can do this through either a [`yaml_metadata_block`](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block) or [`pandoc_title_block`](http://pandoc.org/MANUAL.html#extension-pandoc_title_block). It's still unclear to me whether we want the author details section automatically generated in pandoc or inserted as a section at the top of the manuscript. We should feel unconstrained here and do what causes the least technical problems, rather than say what produces the most canonical authorship section.

**Comment by agitter** [comment]
I support a simplified system.  In deep-review I was working backwards, trying to automate a complicated process that I had been executing semi-manually.  That made it harder (for me) to implement in a clean pandas style.  I was also leaving room to extend that initial pull request to do things like more complicated multi-affiliation processing and author ordering.  We don't want to support that here.

Initials can be derived fairly reliably.  However, eventually there will be authors with the same initials so resolving that manually in the table could be a good idea.

Implicit approval by adding information to the table makes sense.
