### ISSUE TITLE
Renaming repository from manubot-rootstock

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#70]
I don't think `manubot-rootstock` is a terrible repo name, but it may not be the best. The two biggest problems I see are that it's:

1. long
2. confusing since many users may not be familiar with rootstocks

Here are some other names I jotted down:

+ manubot-init
+ manubot-model
+ manubot-stemcell
+ manubot-template
+ manucat
+ manucross
+ manumorph
+ manuroot
+ manusource
+ manustart

Alphabetically sorted so I don't bias others with my ranking. Since this would be a slightly disruptive change, we should only make it if we feel any of these names is much better.

CC @cgreene @agitter @slochower. I do like the name "Manubot" for the overall system and the [python package](https://github.com/greenelab/manubot). That's way all of these names stick to the manu* theme.

**Comment by agitter** [comment]
I happen to like `manubot-rootstock`.  I'm not opposed to some of the others here though.   `manubot-template` and `manubot-init` are also descriptive of the purpose, which I prefer.  `manubase` is another short idea.

**Comment by cgreene** [comment]
I don't have a strong feeling. My inclination is not to change a repository that's already named + used.

**Comment by vsmalladi** [comment]
I like `manubot-rootstock`, but am fine with `manubot-template`, since it is very descriptive.

**Comment by slochower** [comment]
I agree exactly with @agitter.

**Comment by dhimmel** [comment]
My favorite is `manuroot`, but given that others don't feel strongly about a name change, let's leave it. I'll close this issue for now. If anyone does start to feel strongly that there is a more advantageous name than manubot-rootstock, leave a comment.

> My inclination is not to change a repository that's already named + used.

It is a bit disruptive, but GitHub does a good job redirecting links when repos are renamed. However, given that we're targeting a large user base (1000s of users), I think small changes that will help down the road are likely worth it.
