### ISSUE TITLE
MIT licensed JS code

### ISSUE THREAD

**Issue by rgieseke** [greenelab/manubot-rootstock#73]
The `anchor` script (https://github.com/greenelab/manubot-rootstock/blob/master/build/assets/anchors.js) is not yet listed in the licensing section of the Readme.

I think it would be good to mention this somehow, maybe with "unless noted explicitly" or something similar?

**Comment by dhimmel** [comment]
Good point & I agree.

Want to make a PR? If not, I'll do it.

**Comment by rgieseke** [comment]
Done in #75
