### ISSUE TITLE
gh-publisher: lessons to learn?

### ISSUE THREAD

**Issue by RaoOfPhysics** [greenelab/manubot-rootstock#86]
Have you seen [https://github.com/ewanmellor/gh-publisher](https://github.com/ewanmellor/gh-publisher)? What lessons can we learn from them?

EDIT. Example: http://drphilmarshall.github.io/Ideas-for-Citizen-Science-in-Astronomy/

**Comment by agitter** [comment]
There was some discussion of this in #32 and #33.  Any particular lessons you had in mind?

**Comment by dhimmel** [comment]
Also linking to the resources mentioned in [this Tweet](https://twitter.com/devinberg/status/929466744875442176):

+ [Automatic Documentation Publishing with GitHub and TravisCI ](http://blog.gockelhut.com/2014/09/automatic-documentation-publishing-with.html?m=1)
+ [Continuous Publishing](http://blog.martinfenner.org/2014/03/10/continuous-publishing/)

Unless there are specific things we can add from these projects, close this issue.
