### ISSUE TITLE
SETUP.md repo sed substitution is failing

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#92]
At the [OpenCon do-a-thon](https://github.com/sparcopen/doathon/issues/21), we've had 2 users experience potentially faulty substitutions. Rather than rebranding their README to USER/REPO, their `README.md` is rebranded to USER/USER. Possibly introduced in #84?

The two examples are https://github.com/zambujo/manubot/commit/10397d6a05235c3517ac981b9b3c67920c226b9a are https://github.com/broadwym/manu1/commit/64954e5c18ac22e170ae4a74c8d5877d35ac78a2.

Interestingly one user did not have the issue: https://github.com/schliebs/open_manuscript/commit/77da6c844ac061061c03b93721e7eade90fabd99, making me wonder whether its user error or not.

`SETUP.md` currently [uses](https://github.com/greenelab/manubot-rootstock/blob/64af604e7987bc51b11cac123c6c178201fbaccd/SETUP.md#readme-updates):

```
sed "s/greenelab/$OWNER/g" README.md > tmp && mv -f tmp README.md
sed "s/manubot-rootstock/$REPO/g" README.md > tmp && mv -f tmp README.md
```

@vsmalladi any ideas what could be happening?

**Comment by agitter** [comment]
@dhimmel (or @zambujo and @broadwym) what operating system was used on the failed setup?

**Comment by vsmalladi** [comment]
@dhimmel that is weird, not sure why it would fail since we didn't change the syntax.

**Comment by dhimmel** [comment]
> what operating system was used on the failed setup?

@zambujo was on Linux (had issue), @broadwym was on Windows (had issue), and @schliebs was on Windows (no issue).

> not sure why it would fail since we didn't change the syntax

Yeah me too. Therefore I thought user error is most likely. Although I'm surprised that two people had the same issue. Also @zambujo thought that he didn't make an error.

**Comment by vsmalladi** [comment]
I can try a full test on Mac and see if anything inadvertently changed.

**Comment by vsmalladi** [comment]
@dhimmel I tested this weekend and everything worked fine setting up.

**Comment by dhimmel** [comment]
>  I tested this weekend and everything worked fine setting up.

Cool, I'll close this issue and we'll assume there was user error rather than faulty commands.

One thing I noticed is that the demo users would often retype commands rather than copy and paste, which could be the source of some errors.
