### ISSUE TITLE
Preserving old versions of files on the gh-pages branch via directories

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#96]
The `gh-pages` branch is responsible for the [GitHub Pages site](https://greenelab.github.io/manubot-rootstock) and contains output HTML, PDF, CSS, image, and OTS files. Currently, new manuscript builds overwrite the files, which are in the root directory of this branch:

https://github.com/greenelab/manubot-rootstock/blob/f165f609f33b11fdf71a0db6435d4dd159f23973/ci/deploy.sh#L62-L68

I propose instead creating a directory structure, so all past outputs on `gh-pages` are preserved through versioned directories. The version would be the `master` commit that the build was based on (i.e. `$TRAVIS_COMMIT`). For example, I commit https://github.com/greenelab/manubot-rootstock/commit/f165f609f33b11fdf71a0db6435d4dd159f23973 to master. The outputs that currently go to the root directory of `gh-pages` would instead go to the `v/f165f609f33b11fdf71a0db6435d4dd159f23973` directory (`v` for version). The latest HTML and PDF manuscript would stay available at their current URLs, probably via symbolic links ([see here](https://github.com/s4y/gh-pages-symlink-test) for how symlinks act with GitHub Pages).

We could use [redirects](https://help.github.com/articles/redirects-on-github-pages/), so `v/freeze` redirects to the latest versioned directory.

The benefits of this change are twofold:

1. You can view outdated versions of the HTML manuscript. Right now, you [can only](https://stackoverflow.com/questions/37143667) see the rendered HTML for the latest version.

2. The OpenTimestamp `.ots` files need to be upgraded. Until they're upgraded, they depend on a calendar service for verification. Currently, we haven't upgraded timestamps, which creates the possibility that we may be unable to prove existence if the calendar goes down. Note that the timestamps can only be upgraded after the bitcoin transaction confirms, which could be days. That's why we don't specify `--wait` in our builds. Anyways, previously I was planning on rewriting the `gh-pages` history to upgrade timestamps in past commits. However, rewriting history is dangerous. It would be preferable to be able to upgrade past timestamps without rewriting history, which this proposal would enable.

The main disadvantage I can think of is repository size, since more files are being tracked. However, I'm not sure it'd be any bigger, since all files are currently in the git history at some point. According to [this](https://stackoverflow.com/a/29949004/4651668):

> even if you have multiple files with the same contents but different names or in different locations or from different commits only one copy would ever be saved but with several pointers to it in each commit tree.

Shallow cloning would lose its savings, but I'm not sure we care.

One final point to consider is that a single commit will sometimes be deployed multiple times (say if the CI build is rerun). They will not always be the same. For the same source commit, I think we'd use the latest build.

**Comment by agitter** [comment]
Regarding 1. is the issue on the rendering side?  We have the versions of the html outputs tracked, but it is inconvenient to view them?

I have used https://htmlpreview.github.io as a workaround, which meets my needs for viewing old versions of the manuscript.  For example, 5eba007 is rendered [like this](https://htmlpreview.github.io/?https://github.com/greenelab/manubot-rootstock/blob/5eba0077a83748eed99743511631f2039d4dfccb/index.html).  That does depend on an external resource that can break or go down.

**Comment by dhimmel** [comment]
@agitter htmlpreview is an alternative solution for 1. I've used it in the past, but didn't realize we could use it so easily for hosting old manubot HTML pages. Here are three URLs of htmlpreview for Manubot:

```
https://htmlpreview.github.io/?https://github.com/greenelab/deep-review/blob/81df5e187ad362ffed92610b3ca3ae3a8fcb0774/index.html
https://htmlpreview.github.io/?https://github.com/greenelab/scihub-manuscript/blob/cc8212b85944392fe9f1e1dbc5a069550a2c95bc/index.html
https://htmlpreview.github.io/?https://github.com/greenelab/manubot-rootstock/blob/74b31ccf70cfbacfda79df6d72629aad605c5065/index.html
```

The only thing that I notice failing is embedding SVGs with a local path. Even the Hypothesis dialog appeared!

The directory approach is preferable in terms of the prettiness and navigability of the URL. It's also better for machine readability and SEO to have the actual manuscript HTML as the page source. And I don't think HTML query strings are ideal for permalinks. However, these may be minor issues.

> That does depend on an external resource that can break or go down.

Realistically our dependency footprint would only expand slightly since we're already reliant on GitHub Pages. However, htmlpreview's [lack of license](https://github.com/htmlpreview/htmlpreview.github.com/issues/30) is concerning for longterm persistence.
